var toptabmenu = [
{'id':'1','title':'全 局','mainmenulist':'1','mainmenuidlist':'1010','defaulturl':'rapidset/shortcut.aspx','system':'1'},
{'id':'2','title':'界 面','mainmenulist':'3,2,4','mainmenuidlist':'1210,1110,1310','defaulturl':'global/global_uiandshowstyle.aspx','system':'1'},
{'id':'3','title':'内 容','mainmenulist':'5,10','mainmenuidlist':'1410,1910','defaulturl':'forum/forum_seachtopic.aspx','system':'1'},
{'id':'4','title':'用 户','mainmenulist':'6,7','mainmenuidlist':'1510,1610','defaulturl':'user/usergrid.aspx','system':'1'},
{'id':'5','title':'聚 合','mainmenulist':'8','mainmenuidlist':'1710','defaulturl':'aggregation/aggregation_forumaggset.aspx','system':'1'},
{'id':'6','title':'论 坛','mainmenulist':'9','mainmenuidlist':'1810','defaulturl':'forum/forum_forumstree.aspx','system':'1'},
{'id':'7','title':'扩 展','mainmenulist':'11,16','mainmenuidlist':'2010,2510','defaulturl':'global/global_passportmanage.aspx','system':'2'},
{'id':'8','title':'工 具','mainmenulist':'12,13,14,15','mainmenuidlist':'2110,2210,2310,2410','defaulturl':'global/global_cachemanage.aspx','system':'1'}
];
var mainmenu = [
{'id':'1','menuid':'1010','menutitle':'常规选项'},
{'id':'2','menuid':'1110','menutitle':'编辑器'},
{'id':'3','menuid':'1210','menutitle':'界面风格'},
{'id':'4','menuid':'1310','menutitle':'其他'},
{'id':'5','menuid':'1410','menutitle':'内容管理'},
{'id':'10','menuid':'1910','menutitle':'审核管理'},
{'id':'6','menuid':'1510','menutitle':'用户管理'},
{'id':'7','menuid':'1610','menutitle':'分组与级别'},
{'id':'8','menuid':'1710','menutitle':'论坛聚合'},
{'id':'9','menuid':'1810','menutitle':'版块设置'},
{'id':'11','menuid':'2010','menutitle':'整合设置'},
{'id':'12','menuid':'2110','menutitle':'数据库'},
{'id':'13','menuid':'2210','menutitle':'系统工具'},
{'id':'14','menuid':'2310','menutitle':'论坛维护'},
{'id':'15','menuid':'2410','menutitle':'运行记录'},
{'id':'16','menuid':'2510','menutitle':'云平台'}
];
var submenu = [
{'menuparentid':'1010','menutitle':'站点信息','link':'global/global_siteset.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'站点优化','link':'global/global_siteoptimization.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'站点功能','link':'forum/forum_option.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'搜索引擎优化','link':'global/global_searchengine.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'安全与防灌水','link':'global/global_safecontrol.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'注册与访问控制','link':'global/global_registerandvisit.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'时间段设置','link':'global/global_timespan.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'积分设置','link':'global/global_scoreset.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'附件设置','link':'global/global_attach.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'用户权限','link':'forum/forum_userrights.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'邮箱设置','link':'global/emailconfig.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'广告管理','link':'global/advsgrid.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'论坛公告','link':'global/global_announcegrid.aspx','frameid':'main'},
{'menuparentid':'1010','menutitle':'论坛帮助','link':'global/global_helplist.aspx','frameid':'main'},
{'menuparentid':'1110','menutitle':'编辑器设置','link':'global/global_editorset.aspx','frameid':'main'},
{'menuparentid':'1110','menutitle':'UBB代码','link':'forum/forum_bbcodegrid.aspx','frameid':'main'},
{'menuparentid':'1110','menutitle':'表情管理','link':'forum/forum_smiliemanage.aspx','frameid':'main'},
{'menuparentid':'1210','menutitle':'界面与显示方式','link':'global/global_uiandshowstyle.aspx','frameid':'main'},
{'menuparentid':'1210','menutitle':'模板管理','link':'global/global_templatesgrid.aspx','frameid':'main'},
{'menuparentid':'1210','menutitle':'导航菜单管理','link':'global/global_navigationmanage.aspx','frameid':'main'},
{'menuparentid':'1210','menutitle':'论坛热点','link':'forum/forum_forumhot.aspx','frameid':'main'},
{'menuparentid':'1310','menutitle':'在线列表定制','link':'global/global_onlinelistgrid.aspx','frameid':'main'},
{'menuparentid':'1310','menutitle':'友情链接列表','link':'global/global_forumlinksgrid.aspx','frameid':'main'},
{'menuparentid':'1310','menutitle':'勋章列表','link':'global/global_medalgrid.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'主题管理','link':'forum/forum_seachtopic.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'批量删帖','link':'forum/forum_searchpost.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'附件管理','link':'forum/forum_searchattchment.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'标签管理','link':'forum/forum_tagmanage.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'鉴定管理','link':'forum/forum_identifymanage.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'公共短消息管理','link':'global/global_announceprivatemessage.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'清理短消息','link':'forum/forum_searchsm.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'词语过滤','link':'global/global_wordgrid.aspx','frameid':'main'},
{'menuparentid':'1410','menutitle':'主题回收站','link':'forum/forum_auditingtopic.aspx','frameid':'main'},
{'menuparentid':'1910','menutitle':'审核主题','link':'forum/forum_auditnewtopic.aspx','frameid':'main'},
{'menuparentid':'1910','menutitle':'审核帖子','link':'forum/forum_auditpost.aspx','frameid':'main'},
{'menuparentid':'1510','menutitle':'添加用户','link':'user/adduser.aspx','frameid':'main'},
{'menuparentid':'1510','menutitle':'编辑用户','link':'user/usergrid.aspx','frameid':'main'},
{'menuparentid':'1510','menutitle':'审核新用户','link':'user/audituser.aspx','frameid':'main'},
{'menuparentid':'1510','menutitle':'合并用户','link':'user/combinationuser.aspx','frameid':'main'},
{'menuparentid':'1610','menutitle':'添加用户组','link':'user/addgroup.aspx','frameid':'main'},
{'menuparentid':'1610','menutitle':'编辑用户组','link':'user/editgroup.aspx','frameid':'main'},
{'menuparentid':'1610','menutitle':'合并用户组','link':'user/combinationusergroup.aspx','frameid':'main'},
{'menuparentid':'1710','menutitle':'论坛数据','link':'aggregation/aggregation_forumaggset.aspx','frameid':'main'},
{'menuparentid':'1710','menutitle':'轮显图片','link':'aggregation/aggregation_rotatepic.aspx?pagename=website','frameid':'main'},
{'menuparentid':'1710','menutitle':'推荐版块','link':'aggregation/aggregation_recommendtopic.aspx','frameid':'main'},
{'menuparentid':'1710','menutitle':'论坛热帖','link':'aggregation/aggregation_edithottopic.aspx','frameid':'main'},
{'menuparentid':'1810','menutitle':'版块管理','link':'forum/forum_forumstree.aspx','frameid':'main'},
{'menuparentid':'1810','menutitle':'版块添加','link':'forum/forum_addforums.aspx','frameid':'main'},
{'menuparentid':'1810','menutitle':'合并版块','link':'forum/forum_forumcombination.aspx','frameid':'main'},
{'menuparentid':'1810','menutitle':'主题分类','link':'forum/forum_topictypesgrid.aspx','frameid':'main'},
{'menuparentid':'2010','menutitle':'通行证设置','link':'global/global_passportmanage.aspx','frameid':'main'},
{'menuparentid':'2110','menutitle':'运行指定的SQL语句','link':'global/global_runsql.aspx','frameid':'main'},
{'menuparentid':'2110','menutitle':'数据库日志管理','link':'global/global_logandshrinkdb.aspx','frameid':'main'},
{'menuparentid':'2110','menutitle':'分表设置','link':'global/global_detachtable.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'更新缓存','link':'global/global_cachemanage.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'手动调整版块','link':'forum/forum_forumsgrid.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'推广插件设置','link':'plugin/creditstrategy.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'计划任务','link':'global/global_schedulemanage.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'批量邮件发送','link':'global/global_usergroupsendemail.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'批量短消息发送','link':'global/global_sendsmtogroup.aspx','frameid':'main'},
{'menuparentid':'2310','menutitle':'论坛数据维护','link':'forum/forum_updateforumstatic.aspx','frameid':'main'},
{'menuparentid':'2410','menutitle':'后台日志','link':'tools/adminvisitloggrid.aspx','frameid':'main'},
{'menuparentid':'2410','menutitle':'管理日志','link':'forum/forum_moderatormanagelog.aspx','frameid':'main'},
{'menuparentid':'2410','menutitle':'评分日志','link':'forum/forum_ratescorelog.aspx','frameid':'main'},
{'menuparentid':'2410','menutitle':'勋章授予日志','link':'forum/forum_medalsloggird.aspx','frameid':'main'},
{'menuparentid':'2410','menutitle':'积分交易日志','link':'forum/forum_paymentloggrid.aspx','frameid':'main'},
{'menuparentid':'2210','menutitle':'论坛数据调用','link':'global/global_forumdatacall.aspx','frameid':'main'},
{'menuparentid':'2510','menutitle':'云平台首页','link':'global/global_cloudindex.aspx','frameid':'main'},
{'menuparentid':'2510','menutitle':'云平台设置','link':'global/global_cloudset.aspx','frameid':'main'},
{'menuparentid':'2510','menutitle':'QQ登录设置','link':'global/global_connectset.aspx','frameid':'main'}
];
var shortcut = []